require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CourseCheckListsController do

  # This should return the minimal set of attributes required to create a valid
  # CourseCheckList. As you add validations to CourseCheckList, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "course_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CourseCheckListsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all course_check_lists as @course_check_lists" do
      course_check_list = CourseCheckList.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:course_check_lists)).to eq([course_check_list])
    end
  end

  describe "GET show" do
    it "assigns the requested course_check_list as @course_check_list" do
      course_check_list = CourseCheckList.create! valid_attributes
      get :show, {:id => course_check_list.to_param}, valid_session
      expect(assigns(:course_check_list)).to eq(course_check_list)
    end
  end

  describe "GET new" do
    it "assigns a new course_check_list as @course_check_list" do
      get :new, {}, valid_session
      expect(assigns(:course_check_list)).to be_a_new(CourseCheckList)
    end
  end

  describe "GET edit" do
    it "assigns the requested course_check_list as @course_check_list" do
      course_check_list = CourseCheckList.create! valid_attributes
      get :edit, {:id => course_check_list.to_param}, valid_session
      expect(assigns(:course_check_list)).to eq(course_check_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CourseCheckList" do
        expect {
          post :create, {:course_check_list => valid_attributes}, valid_session
        }.to change(CourseCheckList, :count).by(1)
      end

      it "assigns a newly created course_check_list as @course_check_list" do
        post :create, {:course_check_list => valid_attributes}, valid_session
        expect(assigns(:course_check_list)).to be_a(CourseCheckList)
        expect(assigns(:course_check_list)).to be_persisted
      end

      it "redirects to the created course_check_list" do
        post :create, {:course_check_list => valid_attributes}, valid_session
        expect(response).to redirect_to(CourseCheckList.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved course_check_list as @course_check_list" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(CourseCheckList).to receive(:save).and_return(false)
        post :create, {:course_check_list => { "course_id" => "invalid value" }}, valid_session
        expect(assigns(:course_check_list)).to be_a_new(CourseCheckList)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(CourseCheckList).to receive(:save).and_return(false)
        post :create, {:course_check_list => { "course_id" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested course_check_list" do
        course_check_list = CourseCheckList.create! valid_attributes
        # Assuming there are no other course_check_lists in the database, this
        # specifies that the CourseCheckList created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(CourseCheckList).to receive(:update).with({ "course_id" => "1" })
        put :update, {:id => course_check_list.to_param, :course_check_list => { "course_id" => "1" }}, valid_session
      end

      it "assigns the requested course_check_list as @course_check_list" do
        course_check_list = CourseCheckList.create! valid_attributes
        put :update, {:id => course_check_list.to_param, :course_check_list => valid_attributes}, valid_session
        expect(assigns(:course_check_list)).to eq(course_check_list)
      end

      it "redirects to the course_check_list" do
        course_check_list = CourseCheckList.create! valid_attributes
        put :update, {:id => course_check_list.to_param, :course_check_list => valid_attributes}, valid_session
        expect(response).to redirect_to(course_check_list)
      end
    end

    describe "with invalid params" do
      it "assigns the course_check_list as @course_check_list" do
        course_check_list = CourseCheckList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(CourseCheckList).to receive(:save).and_return(false)
        put :update, {:id => course_check_list.to_param, :course_check_list => { "course_id" => "invalid value" }}, valid_session
        expect(assigns(:course_check_list)).to eq(course_check_list)
      end

      it "re-renders the 'edit' template" do
        course_check_list = CourseCheckList.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(CourseCheckList).to receive(:save).and_return(false)
        put :update, {:id => course_check_list.to_param, :course_check_list => { "course_id" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested course_check_list" do
      course_check_list = CourseCheckList.create! valid_attributes
      expect {
        delete :destroy, {:id => course_check_list.to_param}, valid_session
      }.to change(CourseCheckList, :count).by(-1)
    end

    it "redirects to the course_check_lists list" do
      course_check_list = CourseCheckList.create! valid_attributes
      delete :destroy, {:id => course_check_list.to_param}, valid_session
      expect(response).to redirect_to(course_check_lists_url)
    end
  end

end
